version: 2
jobs:
  build:
    docker:
      - image: 'cimg/node:16.10.0'
      - image: 'docker:17.09.1-ce-git'
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install
      - run:
          name: Build Success
          when: on_success
          command: >
            sudo apt-get update          

            sudo apt install python3-pip

            sudo pip3 install awsebcli --upgrade

            sudo aws ecr get-login-password --region <AWS_REGION>
            
            docker login --username AWS --password-stdin <AWS_ECR_ACCOUNT_URL>

            docker build -t <AWS_RESOURCE_PREFIX> .

            docker tag <AWS_RESOURCE_PREFIX>:latest
            <AWS_ECR_ACCOUNT_URL>/<AWS_RESOURCE_PREFIX>:latest

            docker push <AWS_ECR_ACCOUNT_URL>/<AWS_RESOURCE_PREFIX>:latest
workflows:
  version: 2
  execute_bulk:
    jobs:
      - build
